/**
 * Static fixtures for Finance UI until GraphQL is wired.
 * organizationId is placeholder — no organizations query in mock phase.
 */

import type { MockFinanceAccount, MockFinanceTransaction } from "./finance/types"

export const MOCK_ORGANIZATION_ID = "org-mock-1"

export const MOCK_CURRENCY = "USD"

/** Anchor "today" for deterministic demo month windows (tests can depend on dataset dates). */
export const MOCK_TODAY = "2026-04-20"

export const mockFinanceAccounts: MockFinanceAccount[] = [
  {
    id: "acc-checking",
    organizationId: MOCK_ORGANIZATION_ID,
    name: "Operating — Checking",
    kind: "ASSET",
    currency: MOCK_CURRENCY,
    openingBalanceCents: 250_000,
    description: "Primary cash",
    isActive: true,
  },
  {
    id: "acc-savings",
    organizationId: MOCK_ORGANIZATION_ID,
    name: "Reserve — Savings",
    kind: "ASSET",
    currency: MOCK_CURRENCY,
    openingBalanceCents: 100_000,
    description: null,
    isActive: true,
  },
  {
    id: "cat-revenue",
    organizationId: MOCK_ORGANIZATION_ID,
    name: "Product revenue",
    kind: "INCOME",
    currency: MOCK_CURRENCY,
    openingBalanceCents: 0,
    description: null,
    isActive: true,
  },
  {
    id: "cat-services",
    organizationId: MOCK_ORGANIZATION_ID,
    name: "Services",
    kind: "INCOME",
    currency: MOCK_CURRENCY,
    openingBalanceCents: 0,
    description: null,
    isActive: true,
  },
  {
    id: "cat-rent",
    organizationId: MOCK_ORGANIZATION_ID,
    name: "Rent & facilities",
    kind: "EXPENSE",
    currency: MOCK_CURRENCY,
    openingBalanceCents: 0,
    description: null,
    isActive: true,
  },
  {
    id: "cat-software",
    organizationId: MOCK_ORGANIZATION_ID,
    name: "Software & tooling",
    kind: "EXPENSE",
    currency: MOCK_CURRENCY,
    openingBalanceCents: 0,
    description: null,
    isActive: true,
  },
]

export const mockFinanceTransactions: MockFinanceTransaction[] = [
  {
    id: "txn-1",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-04-18",
    type: "INCOME",
    amountCents: 500_000,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-revenue",
    description: "April product billing",
    reference: "INV-1042",
    status: "POSTED",
  },
  {
    id: "txn-2",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-04-17",
    type: "EXPENSE",
    amountCents: 120_000,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-rent",
    description: "Office rent",
    reference: "LEASE-04",
    status: "POSTED",
  },
  {
    id: "txn-3",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-04-15",
    type: "EXPENSE",
    amountCents: 4_900,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-software",
    description: "Cloud hosting",
    status: "POSTED",
  },
  {
    id: "txn-4",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-04-10",
    type: "INCOME",
    amountCents: 95_000,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-services",
    description: "Consulting milestone",
    reference: "SOW-88",
    status: "POSTED",
  },
  {
    id: "txn-5",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-03-28",
    type: "EXPENSE",
    amountCents: 2_400,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-software",
    description: "Design tooling",
    status: "POSTED",
  },
  {
    id: "txn-6",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-03-05",
    type: "INCOME",
    amountCents: 420_000,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-revenue",
    description: "March product billing",
    status: "POSTED",
  },
  {
    id: "txn-7",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-02-14",
    type: "EXPENSE",
    amountCents: 118_000,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-rent",
    description: "Office rent",
    status: "POSTED",
  },
  {
    id: "txn-8",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-02-01",
    type: "INCOME",
    amountCents: 380_000,
    currency: MOCK_CURRENCY,
    accountId: "acc-savings",
    categoryId: "cat-revenue",
    description: "February product billing",
    status: "POSTED",
  },
  {
    id: "txn-9",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-04-20",
    type: "INCOME",
    amountCents: 25_000,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-services",
    description: "Services accrual",
    status: "POSTED",
  },
  {
    id: "txn-10",
    organizationId: MOCK_ORGANIZATION_ID,
    date: "2026-01-12",
    type: "EXPENSE",
    amountCents: 15_000,
    currency: MOCK_CURRENCY,
    accountId: "acc-checking",
    categoryId: "cat-software",
    description: "Annual license true-up",
    status: "POSTED",
  },
]
